### ISSUE TITLE
[VMOE]Pre-trained models based on ImageNet-1k instead of ImageNet-21k

### ISSUE THREAD

**Issue by firestonelib** [google-research/vmoe#5]
The VMOE model is great. I wonder when the pre-trained config would be made available? The pre-trained models  are all based on the ImageNet-21k data, which makes sense and great. But could you guys also release the pre-trained models based on ImageNet-1k? That could be very helpful for benchmark and comparisons.

Thanks and looking forward to your responses.

**Comment by jpuigcerver** [comment]
The [config file](https://github.com/google-research/vmoe/blob/652f8bd5ec2ee5b7733f23d1cf733bc362099e1a/vmoe/configs/vmoe_paper/vmoe_s32_last2_ilsvrc2012_randaug_light1.py) that produced the S/32 model with 2 MoE layers has been open sourced.

**Comment by jacoblam3112** [comment]
@jpuigcerver I would like to ask if you trained a similar size non-MoE version of ViT-S/32 on ImageNet-1k dataset to compare its performance with the MoE version that you released ?
I wonder if the non-MoE version will have super performance than the MoE version due to the Imagenet-1k dataset size being very small ? Any guess or comment on that ?

**Comment by jpuigcerver** [comment]
@jacoblam3112 we didn't train a dense ViT-S/32 ourselves, but we compared with results from previously published dense models trained on ImageNet-21k, in Figure 38 from the paper https://arxiv.org/pdf/2106.05974.

On ImageNet-1k (~1.3M images), our original MoE probably works worse than a dense model because of overfitting. I haven't tried we more recent techniques (newer routing algorithms, training recipes, etc), though.
